[package]
name = "kernel"
version = "0.6.0"
edition = "2024"

[profile.dev]
opt-level = "s"

[profile.release]
opt-level = "s"
lto = true

[lib]
name = "kernel"
edition = "2024"
path = "src/kernel.rs"
crate-type = ["staticlib"]
test = false
bench = false

[dependencies]
pbkdf2 = { version = "0.12", default-features = false, features = ["hmac"] }
sha2 = { version = "0.10", default-features = false }


[build-dependencies]
rustc-demangle = "0.1"
